function [BW1,maskedRGBImage1] = CombinedMask(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 16-Nov-2021
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.974;
channel1Max = 0.068;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.397;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.223;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = ( (I(:,:,1) >= channel1Min) | (I(:,:,1) <= channel1Max) ) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;



%Green Mask


%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 19-Nov-2021
%------------------------------------------------------


% Convert RGB image to chosen color space
I1 = rgb2hsv(maskedRGBImage);

% Define thresholds for channel 1 based on histogram settings
channel1Min1 = 0.236;
channel1Max1 = 0.375;

% Define thresholds for channel 2 based on histogram settings
channel2Min1 = 0.340;
channel2Max1 = 0.810;

% Define thresholds for channel 3 based on histogram settings
channel3Min1 = 0.097;
channel3Max1 = 0.210;

% Create mask based on chosen histogram thresholds
sliderBW1 = (I1(:,:,1) >= channel1Min1 ) & (I1(:,:,1) <= channel1Max1) & ...
    (I1(:,:,2) >= channel2Min1 ) & (I1(:,:,2) <= channel2Max1) & ...
    (I1(:,:,3) >= channel3Min1 ) & (I1(:,:,3) <= channel3Max1);
BW1 = sliderBW1 ;

% Initialize output masked image based on input image.
maskedRGBImage1 = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage1(repmat(~BW1,[1 1 3])) = 0;


end
